import "dotenv/config";
import { db } from "../src/db";
import { projects } from "../src/db/schema";
import { IMG } from "../src/lib/images";

type Seed = Omit<
  typeof projects.$inferInsert,
  "id" | "createdAt"
>;

const rows: Seed[] = [
  {
    slug: "domus-blanc-boutique-hotel",
    title: "Domus Blanc Boutique Hotel",
    category: "Boutique Hotel",
    location: "Chania Town",
    tagline: "A restored neoclassical landmark in the heart of Chania.",
    description:
      "Originally the French Consulate, this neoclassical building was fully restored by Hellenic Homes into a 12-suite heritage hotel. Original stonework and proportions were preserved and paired with contemporary comfort — a walled garden, plunge pool and ground-floor bistro now complete one of the city's most quietly distinguished addresses.",
    status: "Completed",
    year: 2024,
    units: 12,
    areaSqm: 1450,
    imageUrl: IMG.elegantBedroom,
    gallery: [IMG.suiteDaylight, IMG.chaniaHarbor, IMG.stoneAlley],
    highlights: ["Heritage restoration", "12 suites", "Garden & plunge pool", "Bistro"],
    featured: true,
    position: 1,
  },
  {
    slug: "nama-splash-resort-hotel",
    title: "Nama Splash Resort Hotel",
    category: "Resort Hotel",
    location: "Daratsos, Chania",
    tagline: "A contemporary 114-room resort minutes from the sea.",
    description:
      "A modern Mediterranean resort development in Daratsos, featuring 114 rooms and suites with swim-up access and shaded terraces. The architecture prioritises light, shade and water — a layered plan that reads as a single, coherent resort rather than a collection of blocks.",
    status: "Under Construction",
    year: 2026,
    units: 114,
    areaSqm: 8200,
    imageUrl: IMG.poolMediterranean,
    gallery: [IMG.villaSea, IMG.villaPatio],
    highlights: ["114 rooms & suites", "Swim-up access", "Resort master plan", "Mediterranean design"],
    featured: true,
    position: 2,
  },
  {
    slug: "kyma-seafront-apartments",
    title: "Kyma Seafront Apartments",
    category: "Apartments",
    location: "Kolymvari, Chania",
    tagline: "Four fully finished apartments on the water's edge.",
    description:
      "A compact seafront development in Kolymvari comprising four fully equipped apartments, renovated for comfortable year-round coastal living. Generous glazing frames the horizon, while durable, low-maintenance finishes keep the focus on the sea.",
    status: "Completed",
    year: 2023,
    units: 4,
    areaSqm: 320,
    imageUrl: IMG.seasideSunny,
    gallery: [IMG.villaPool, IMG.patioRattan],
    highlights: ["Front-line sea views", "4 apartments", "Turnkey finish", "Year-round comfort"],
    featured: false,
    position: 3,
  },
  {
    slug: "melanthia-villas",
    title: "Melanthia Villas",
    category: "Luxury Villas",
    location: "Tsivaras, Chania",
    tagline: "Two private villas of stone, light and water.",
    description:
      "Two luxury villas near Almyrida, combining modern architecture with local stone craftsmanship and private pools. Oriented for privacy and sun, each villa offers serene Mediterranean living a short drive from the beach.",
    status: "Completed",
    year: 2023,
    units: 2,
    areaSqm: 460,
    imageUrl: IMG.villaSea,
    gallery: [IMG.villaTwilight, IMG.villaPatio],
    highlights: ["2 villas", "Private pools", "Local stone", "Near Almyrida beach"],
    featured: true,
    position: 4,
  },
  {
    slug: "markakis-estate",
    title: "Markakis Estate",
    category: "Private Estate",
    location: "Embrosneros, Chania",
    tagline: "A stone-built estate rooted in Cretan tradition.",
    description:
      "A stone-built luxury estate in Embrosneros, designed and constructed to blend traditional Cretan architecture with modern functionality. The estate hosts private stays and exclusive events, set within landscaped grounds that respect the village's rural character.",
    status: "Completed",
    year: 2022,
    units: 1,
    areaSqm: 780,
    imageUrl: IMG.stoneHouse,
    gallery: [IMG.stoneAlley, IMG.creteVillaGarden, IMG.cobblestoneStreet],
    highlights: ["Traditional stonework", "Event hosting", "Landscaped grounds", "Rural setting"],
    featured: false,
    position: 5,
  },
  {
    slug: "sfakianaki-apartments",
    title: "Sfakianaki St. Apartments",
    category: "Apartments",
    location: "Chania Town",
    tagline: "Nineteen refined residences in central Chania.",
    description:
      "A contemporary residential development on I. Sfakianaki Street in central Chania, featuring 19 apartments with functional layouts, premium materials and a refined urban character. Each residence is planned for natural light and quiet, efficient living in the city.",
    status: "Completed",
    year: 2024,
    units: 19,
    areaSqm: 2100,
    imageUrl: IMG.aptBlueSky,
    gallery: [IMG.aptGlassBalcony, IMG.urbanArch],
    highlights: ["19 apartments", "Premium materials", "City-centre", "Energy efficient"],
    featured: false,
    position: 6,
  },
  {
    slug: "miraida-exclusive-residence",
    title: "Miraida Exclusive Residence",
    category: "Luxury Villa",
    location: "Almyrida, Chania",
    tagline: "A hillside villa with panoramic sea views, delivered turnkey.",
    description:
      "A luxury hillside villa in Almyrida, featuring refined architecture and panoramic sea views delivered turnkey — with full interior and exterior completion. Indoor and outdoor living flow together toward the view, framed by mature planting and a private pool.",
    status: "Completed",
    year: 2024,
    units: 1,
    areaSqm: 410,
    imageUrl: IMG.oceanviewSunset,
    gallery: [IMG.poolMediterranean, IMG.villaPool],
    highlights: ["Panoramic sea views", "Turnkey delivery", "Private pool", "Full interior fit-out"],
    featured: true,
    position: 7,
  },
  {
    slug: "pyrgos-springs-residences",
    title: "Pyrgos Springs",
    category: "Residences",
    location: "Pyrgos Psilonerou, Chania",
    tagline: "Seventeen modern homes a short walk from the beach.",
    description:
      "A residential complex in Pyrgos Psilonerou featuring 17 modern homes with shared pools, landscaped areas and direct proximity to the beach. The master plan balances community and privacy, with generous outdoor living throughout.",
    status: "Under Construction",
    year: 2026,
    units: 17,
    areaSqm: 2900,
    imageUrl: IMG.villaPatio,
    gallery: [IMG.mediterraneanHouse, IMG.villaOrangeRoof],
    highlights: ["17 homes", "Shared pools", "Beach proximity", "Landscaped grounds"],
    featured: false,
    position: 8,
  },
  {
    slug: "aurea-villas",
    title: "Aurea Villas",
    category: "Luxury Villas",
    location: "Tsikalaria, Chania",
    tagline: "Two contemporary villas of stone and calm.",
    description:
      "Two luxury villas in Tsikalaria, combining modern design, local stone craftsmanship and private pools for serene Mediterranean living. Clean lines and natural materials give each villa a calm, considered presence on its plot.",
    status: "Under Construction",
    year: 2026,
    units: 2,
    areaSqm: 480,
    imageUrl: IMG.villaTwilight,
    gallery: [IMG.villaSea, IMG.creteVillaGarden],
    highlights: ["2 villas", "Private pools", "Local stone", "Modern design"],
    featured: true,
    position: 9,
  },
  {
    slug: "harma-city-living",
    title: "Harma City Living Apartments",
    category: "Apartments",
    location: "Chania Town",
    tagline: "Eight modern residences for flexible urban living.",
    description:
      "A contemporary apartment complex in central Chania, featuring eight modern residences designed for comfort, style and flexible urban living. Thoughtful plans and a restrained material palette keep the focus on light and proportion.",
    status: "Completed",
    year: 2023,
    units: 8,
    areaSqm: 980,
    imageUrl: IMG.aptGlassBalcony,
    gallery: [IMG.aptBlueSky, IMG.aptGeometric],
    highlights: ["8 residences", "Flexible layouts", "Central location", "Contemporary design"],
    featured: false,
    position: 10,
  },
  {
    slug: "aurora-villa",
    title: "Aurora Villa",
    category: "Luxury Villa",
    location: "Agios Mathaios, Chania",
    tagline: "A five-bedroom villa of natural stone and open views.",
    description:
      "A luxury five-bedroom villa in Agios Mathaios, combining natural stone construction, panoramic views and high-end amenities for refined family living. Generous living spaces open to terraces and a pool oriented to the landscape.",
    status: "Completed",
    year: 2022,
    units: 1,
    areaSqm: 540,
    imageUrl: IMG.creteVillaGarden,
    gallery: [IMG.villaOrangeRoof, IMG.mediterraneanHouse],
    highlights: ["5 bedrooms", "Natural stone", "Panoramic views", "Family living"],
    featured: false,
    position: 11,
  },
  {
    slug: "stalos-concept",
    title: "Stalos Concept",
    category: "Luxury Villas",
    location: "Kato Stalos, Chania",
    tagline: "Three contemporary villas near the coast.",
    description:
      "A new residential development in Kato Stalos featuring three contemporary villas built by Hellenic Homes — combining modern architecture, natural materials and private pools for refined Mediterranean living close to the beach.",
    status: "Under Construction",
    year: 2026,
    units: 3,
    areaSqm: 690,
    imageUrl: IMG.villaOrangeRoof,
    gallery: [IMG.villaTerracotta, IMG.poolMediterranean],
    highlights: ["3 villas", "Private pools", "Natural materials", "Near the beach"],
    featured: false,
    position: 12,
  },
  {
    slug: "galatas-exclusive-residence",
    title: "Galatas Exclusive Residence",
    category: "Private Residence",
    location: "Galatas, Chania",
    tagline: "A high-end residence built for performance and calm.",
    description:
      "A high-end private residence in Galatas, developed by Hellenic Homes to combine durable construction, energy efficiency and refined contemporary design. The home is planned around its garden and the Cretan light.",
    status: "Completed",
    year: 2023,
    units: 1,
    areaSqm: 360,
    imageUrl: IMG.mediterraneanHouse,
    gallery: [IMG.villaTerracotta, IMG.urbanArch],
    highlights: ["Energy efficient", "Durable build", "Garden-oriented", "Contemporary design"],
    featured: false,
    position: 13,
  },
  {
    slug: "gerola-apartments",
    title: "Gerola Apartments",
    category: "Apartments",
    location: "Chania Town",
    tagline: "Seventeen apartments across six levels — a Ten Brinke partnership.",
    description:
      "A modern residential development in the heart of Chania, created through the collaboration of Ten Brinke and Hellenic Homes. Extending across six levels, the building features 17 apartments with a consistent standard of finish and a strong urban presence.",
    status: "Under Construction",
    year: 2026,
    units: 17,
    areaSqm: 3400,
    imageUrl: IMG.urbanArch,
    gallery: [IMG.aptGlassBalcony, IMG.aptBlueSky],
    highlights: ["17 apartments", "Six levels", "Ten Brinke partnership", "City-centre"],
    featured: false,
    position: 14,
  },
  {
    slug: "aloe-suites",
    title: "Aloe Suites",
    category: "Boutique Hotel",
    location: "Almyrida, Chania",
    tagline: "A seafront adults-only hotel of 57 award-winning suites.",
    description:
      "A seafront adults-only boutique hotel in Almyrida, fully designed and constructed by Hellenic Homes. Its 57 suites combine contemporary Mediterranean architecture with award-winning construction quality — a landmark for refined coastal hospitality.",
    status: "Completed",
    year: 2024,
    units: 57,
    areaSqm: 5600,
    imageUrl: IMG.villaPool,
    gallery: [IMG.cabana, IMG.poolMediterranean],
    highlights: ["57 suites", "Seafront", "Adults-only", "Award-winning build"],
    featured: true,
    position: 15,
  },
];

async function main() {
  console.log(`Seeding ${rows.length} projects…`);
  for (const row of rows) {
    await db
      .insert(projects)
      .values(row)
      .onConflictDoNothing({ target: projects.slug });
  }
  console.log("Seed complete.");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
